#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-List-UtilsBy
Version  : 0.11
Release  : 5
URL      : http://search.cpan.org/CPAN/authors/id/P/PE/PEVANS/List-UtilsBy-0.11.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/P/PE/PEVANS/List-UtilsBy-0.11.tar.gz
Summary  : 'higher-order list utility functions'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-List-UtilsBy-doc

%description
NAME
List::UtilsBy - higher-order list utility functions
SYNOPSIS
use List::UtilsBy qw( nsort_by min_by );

use File::stat qw( stat );
my @files_by_age = nsort_by { stat($_)->mtime } @files;

my $shortest_name = min_by { length } @names;

%package doc
Summary: doc components for the perl-List-UtilsBy package.
Group: Documentation

%description doc
doc components for the perl-List-UtilsBy package.


%prep
%setup -q -n List-UtilsBy-0.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/List/UtilsBy.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
